name: Deploy Supabase Function

on:
  push:
    branches:
      - main
    paths:
      - mapme-microservices/supabase/functions/**
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  Deploy-Edge-Functions:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: qsnuignbeuiqzmiksjty

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Functions
        run: supabase functions deploy --project-ref $PROJECT_ID
