name: Run Edge Function Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - mapme-microservices/**
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - mapme-microservices/**

jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      PROJECT_ID: qsnuignbeuiqzmiksjty

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.6

      - name: Run Tests
        working-directory: ./mapme-microservices/supabase/functions/tests
        run: deno test --allow-net --allow-env --allow-read .